/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as DashboardRouteRouteImport } from "./routes/dashboard/route";
import { Route as authRouteRouteImport } from "./routes/(auth)/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as authSignupRouteImport } from "./routes/(auth)/signup";
import { Route as authLoginRouteImport } from "./routes/(auth)/login";
import { ServerRoute as ApiSettingsServerRouteImport } from "./routes/api/settings";
import { ServerRoute as ApiShopifyInstallServerRouteImport } from "./routes/api/shopify/install";
import { ServerRoute as ApiShopifyCallbackServerRouteImport } from "./routes/api/shopify/callback";
import { ServerRoute as ApiGmailCallbackServerRouteImport } from "./routes/api/gmail/callback";
import { ServerRoute as ApiGmailAuthServerRouteImport } from "./routes/api/gmail/auth";
import { ServerRoute as ApiCronGmailPollServerRouteImport } from "./routes/api/cron/gmail-poll";
import { ServerRoute as ApiAuthSplatServerRouteImport } from "./routes/api/auth/$";

const rootServerRouteImport = createServerRootRoute();

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const authRouteRoute = authRouteRouteImport.update({
  id: "/(auth)",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => DashboardRouteRoute,
} as any);
const authSignupRoute = authSignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => authRouteRoute,
} as any);
const authLoginRoute = authLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => authRouteRoute,
} as any);
const ApiSettingsServerRoute = ApiSettingsServerRouteImport.update({
  id: "/api/settings",
  path: "/api/settings",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiShopifyInstallServerRoute = ApiShopifyInstallServerRouteImport.update({
  id: "/api/shopify/install",
  path: "/api/shopify/install",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiShopifyCallbackServerRoute =
  ApiShopifyCallbackServerRouteImport.update({
    id: "/api/shopify/callback",
    path: "/api/shopify/callback",
    getParentRoute: () => rootServerRouteImport,
  } as any);
const ApiGmailCallbackServerRoute = ApiGmailCallbackServerRouteImport.update({
  id: "/api/gmail/callback",
  path: "/api/gmail/callback",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiGmailAuthServerRoute = ApiGmailAuthServerRouteImport.update({
  id: "/api/gmail/auth",
  path: "/api/gmail/auth",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiCronGmailPollServerRoute = ApiCronGmailPollServerRouteImport.update({
  id: "/api/cron/gmail-poll",
  path: "/api/cron/gmail-poll",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof authRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/settings": typeof SettingsRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof authRouteRouteWithChildren;
  "/settings": typeof SettingsRoute;
  "/login": typeof authLoginRoute;
  "/signup": typeof authSignupRoute;
  "/dashboard": typeof DashboardIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/(auth)": typeof authRouteRouteWithChildren;
  "/dashboard": typeof DashboardRouteRouteWithChildren;
  "/settings": typeof SettingsRoute;
  "/(auth)/login": typeof authLoginRoute;
  "/(auth)/signup": typeof authSignupRoute;
  "/dashboard/": typeof DashboardIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/settings"
    | "/login"
    | "/signup"
    | "/dashboard/";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/settings" | "/login" | "/signup" | "/dashboard";
  id:
    | "__root__"
    | "/"
    | "/(auth)"
    | "/dashboard"
    | "/settings"
    | "/(auth)/login"
    | "/(auth)/signup"
    | "/dashboard/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  authRouteRoute: typeof authRouteRouteWithChildren;
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren;
  SettingsRoute: typeof SettingsRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/settings": typeof ApiSettingsServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/cron/gmail-poll": typeof ApiCronGmailPollServerRoute;
  "/api/gmail/auth": typeof ApiGmailAuthServerRoute;
  "/api/gmail/callback": typeof ApiGmailCallbackServerRoute;
  "/api/shopify/callback": typeof ApiShopifyCallbackServerRoute;
  "/api/shopify/install": typeof ApiShopifyInstallServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/settings": typeof ApiSettingsServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/cron/gmail-poll": typeof ApiCronGmailPollServerRoute;
  "/api/gmail/auth": typeof ApiGmailAuthServerRoute;
  "/api/gmail/callback": typeof ApiGmailCallbackServerRoute;
  "/api/shopify/callback": typeof ApiShopifyCallbackServerRoute;
  "/api/shopify/install": typeof ApiShopifyInstallServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/settings": typeof ApiSettingsServerRoute;
  "/api/auth/$": typeof ApiAuthSplatServerRoute;
  "/api/cron/gmail-poll": typeof ApiCronGmailPollServerRoute;
  "/api/gmail/auth": typeof ApiGmailAuthServerRoute;
  "/api/gmail/callback": typeof ApiGmailCallbackServerRoute;
  "/api/shopify/callback": typeof ApiShopifyCallbackServerRoute;
  "/api/shopify/install": typeof ApiShopifyInstallServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths:
    | "/api/settings"
    | "/api/auth/$"
    | "/api/cron/gmail-poll"
    | "/api/gmail/auth"
    | "/api/gmail/callback"
    | "/api/shopify/callback"
    | "/api/shopify/install";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to:
    | "/api/settings"
    | "/api/auth/$"
    | "/api/cron/gmail-poll"
    | "/api/gmail/auth"
    | "/api/gmail/callback"
    | "/api/shopify/callback"
    | "/api/shopify/install";
  id:
    | "__root__"
    | "/api/settings"
    | "/api/auth/$"
    | "/api/cron/gmail-poll"
    | "/api/gmail/auth"
    | "/api/gmail/callback"
    | "/api/shopify/callback"
    | "/api/shopify/install";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiSettingsServerRoute: typeof ApiSettingsServerRoute;
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute;
  ApiCronGmailPollServerRoute: typeof ApiCronGmailPollServerRoute;
  ApiGmailAuthServerRoute: typeof ApiGmailAuthServerRoute;
  ApiGmailCallbackServerRoute: typeof ApiGmailCallbackServerRoute;
  ApiShopifyCallbackServerRoute: typeof ApiShopifyCallbackServerRoute;
  ApiShopifyInstallServerRoute: typeof ApiShopifyInstallServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/(auth)": {
      id: "/(auth)";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof authRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/";
      fullPath: "/dashboard/";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof DashboardRouteRoute;
    };
    "/(auth)/signup": {
      id: "/(auth)/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof authSignupRouteImport;
      parentRoute: typeof authRouteRoute;
    };
    "/(auth)/login": {
      id: "/(auth)/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof authLoginRouteImport;
      parentRoute: typeof authRouteRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/api/settings": {
      id: "/api/settings";
      path: "/api/settings";
      fullPath: "/api/settings";
      preLoaderRoute: typeof ApiSettingsServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/shopify/install": {
      id: "/api/shopify/install";
      path: "/api/shopify/install";
      fullPath: "/api/shopify/install";
      preLoaderRoute: typeof ApiShopifyInstallServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/shopify/callback": {
      id: "/api/shopify/callback";
      path: "/api/shopify/callback";
      fullPath: "/api/shopify/callback";
      preLoaderRoute: typeof ApiShopifyCallbackServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/gmail/callback": {
      id: "/api/gmail/callback";
      path: "/api/gmail/callback";
      fullPath: "/api/gmail/callback";
      preLoaderRoute: typeof ApiGmailCallbackServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/gmail/auth": {
      id: "/api/gmail/auth";
      path: "/api/gmail/auth";
      fullPath: "/api/gmail/auth";
      preLoaderRoute: typeof ApiGmailAuthServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/cron/gmail-poll": {
      id: "/api/cron/gmail-poll";
      path: "/api/cron/gmail-poll";
      fullPath: "/api/cron/gmail-poll";
      preLoaderRoute: typeof ApiCronGmailPollServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute;
  authSignupRoute: typeof authSignupRoute;
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
};

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
);

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute;
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
};

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSettingsServerRoute: ApiSettingsServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiCronGmailPollServerRoute: ApiCronGmailPollServerRoute,
  ApiGmailAuthServerRoute: ApiGmailAuthServerRoute,
  ApiGmailCallbackServerRoute: ApiGmailCallbackServerRoute,
  ApiShopifyCallbackServerRoute: ApiShopifyCallbackServerRoute,
  ApiShopifyInstallServerRoute: ApiShopifyInstallServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
